name: Build and Release Tauri App

on:
  push:
    tags:
      - "v*" # Triggers only on version tags

jobs:
  release:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install Tauri dependencies
        run: yarn install

      - name: Increase version in package.json
        id: version
        run: |
          NEW_VERSION=$(npm version patch --no-git-tag-version)
          echo "NEW_VERSION=${NEW_VERSION}" >> $GITHUB_ENV

      - name: Update version in tauri.conf.prod.json
        run: |
          sed -i 's/"version": "[^"]*"/"version": "'"${NEW_VERSION}"'"/' src-tauri/tauri.conf.prod.json

      - name: Build Tauri app for macOS
        run: yarn build:mac:prod

      - name: Create release on GitHub
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.NEW_VERSION }}
          release_name: Release ${{ steps.version.outputs.NEW_VERSION }}
          draft: false
          prerelease: false

      - name: Upload Tauri artifact
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path:
            ./src-tauri/target/aarch64-apple-darwin/release/bundle/dmg/MKTodo_${{
            steps.version.outputs.NEW_VERSION }}_aarch64.dmg
          asset_name: MKTodo_${{ steps.version.outputs.NEW_VERSION }}_aarch64.dmg
          asset_content_type: application/x-apple-diskimage
